
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agenda_institucional
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - agenda_institucional

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - "5432:5432"
    volumes:
      - db_agenda_institucional:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
    networks:
      - agenda_institucional

networks:
  agenda_institucional:

volumes:
  db_agenda_institucional:
